#!/usr/bin/env node
/** Package the original simulation as an ES module, without changing its rules. */
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '../..');
const levelFiles = fs.readdirSync(path.join(root, 'levels'))
  .filter((name) => /^level-\d+\.json$/.test(name)).sort();
const levels = levelFiles.map((name) => JSON.parse(fs.readFileSync(path.join(root, 'levels', name), 'utf8')));

const sources = [
  'constants.js', 'power-ups.js',
  'entities/ball.js', 'entities/paddle.js', 'entities/brick.js',
  'entities/brick-field.js', 'entities/power-up-drop.js', 'entities/particle.js',
  'physics/collision.js', 'physics/physics-world.js', 'systems/score-system.js',
  'audio/audio-manager.js', 'scenes/game-scene.js',
  'image/median-cut.js', 'image/brick-mapper.js',
];
const code = sources.map((source) => {
  let body = fs.readFileSync(path.join(root, 'src', source), 'utf8');
  if (source === 'constants.js') {
    const marker = '// __LEVEL_DATA_PLACEHOLDER__';
    if (!body.includes(marker)) throw new Error('Legacy level injection marker is missing.');
    body = body.replace(marker, `const LEVEL_DATA = ${JSON.stringify(levels)};`);
  }
  return body;
}).join('\n\n');

const output = '// Generated by node web/game/build-legacy.cjs. Edit src/ for shared gameplay changes.\n'
  + code + '\n\nexport { C, Theme, PowerUpType, POWER_UP_WEIGHTS, POWER_UP_DROP_CHANCE,\n'
  + '  Ball, Paddle, Brick, BrickField, PowerUpDrop, Particle, PhysicsWorld,\n'
  + '  CollisionDetector, ScoreSystem, GameScene, BrickMapper, MedianCut, audio,\n'
  + '  LEVEL_DATA, getPresetLevel, getTotalLevels, _applyColors };\n';
const target = path.join(__dirname, 'legacy.js');
if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== output) {
  fs.writeFileSync(target, output);
}
console.log(`Gameplay module: ${sources.length} original sources, ${levels.length} original levels.`);
